external_components:
  - source:
      type: git
      url: https://github.com/uncle-yura/esphome-ld2450
      ref: master
    components: [ ld2450 ]

uart:
  id: uart_bus
  tx_pin: 
    number: GPIO0
    mode:
      input: true
      pullup: true
  rx_pin: 
    number: GPIO1
    mode:
      input: true
      pullup: true
  baud_rate: 256000
  rx_buffer_size: 512
  parity: NONE
  stop_bits: 1
  data_bits: 8

ld2450:
  uart_id: uart_bus
  update_interval: 500ms
  invert_y: false
  invert_x: false

binary_sensor:
  - platform: ld2450
    has_target:
      name: Presence
    has_moving_target:
      name: Target Moving
    has_still_target:
      name: Target Still

button:
  - platform: restart
    name: "ESP Restart"
  - platform: ld2450
    factory_reset:
      name: "Factory reset"
    reboot:
      name: "Reboot"

switch:
  - platform: ld2450
    single_target:
      name: "Single target"
    bluetooth:
      name: "Bluetooth"

sensor:
  - platform: ld2450
    target_count:
      name: Target Count

    person_0:
      position_x:
        name: "T0-X"  
      position_y:
        name: "T0-Y"  
      speed:
        name: "T0-Speed"  
      resolution:
        name: "T0-Res"  

    person_1:
      position_x:
        name: "T1-X"  
      position_y:
        name: "T1-Y"  
      speed:
        name: "T1-Speed"  
      resolution:
        name: "T1-Res"  

    person_2:
      position_x:
        name: "T2-X"  
      position_y:
        name: "T2-Y"  
      speed:
        name: "T2-Speed"  
      resolution:
        name: "T2-Res"  
